"""Pure Markdown documentation generator for NoUI MCP servers.

Input  : tool_defs (list[dict]) from tools.json
Output : Markdown string written to API.md

Never reads files or calls external services.
"""

from __future__ import annotations

from datetime import UTC, datetime

# ---------------------------------------------------------------------------
# Sensitivity filters
# ---------------------------------------------------------------------------

_AUTH_HEADER_NAMES = frozenset(
    {
        "authorization",
        "cookie",
        "set-cookie",
        "x-api-key",
        "api-key",
        "x-auth-token",
        "x-csrf-token",
        "x-xsrf-token",
        "proxy-authorization",
        "x-goog-authuser",
        "x-client-data",
    }
)

_SENSITIVE_BODY_KEYS = frozenset(
    {
        "password",
        "secret",
        "token",
        "api_key",
        "apikey",
        "access_token",
        "refresh_token",
        "client_secret",
        "private_key",
        "session",
        "sid",
    }
)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_api_markdown(
    *,
    server_id: str,
    app_name: str,
    app_slug: str,  # noqa: ARG001 – reserved for future fingerprint
    workflow_name: str,
    tool_defs: list[dict],
    tabby_profile_id: str,
    generated_at: str | None = None,
    existing: str | None = None,
) -> str:
    """Return the full API.md content for a generated MCP server.

    Args:
        existing: Optional prior file contents. If provided, `<!-- custom:start:NAME -->`
            regions in `existing` are spliced into the freshly-rendered output,
            preserving hand-edited notes across regeneration.
    """
    if generated_at is None:
        generated_at = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines: list[str] = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines.append(f"# API Reference: {app_name}")
    lines.append("")
    lines.append(f"> **Generated by NoUI** on {generated_at}.")
    lines.append(f"> Source server: `{server_id}`")
    lines.append(f"> Workflow: {workflow_name}")
    lines.append(">")
    lines.append("> Do not store secrets in this file.")
    lines.append(
        f"> Regenerate after changing tools: `.venv/bin/python cli/main.py mcp docs {server_id}`"
    )
    lines.append("")

    if not tool_defs:
        lines.append("No APIs detected.")
        return "\n".join(lines)

    # ── Summary table ─────────────────────────────────────────────────────────
    lines.append("## Summary")
    lines.append("")
    lines.append("| Tool | Method | Path | Auth |")
    lines.append("|---|---|---|---|")
    for td in tool_defs:
        name = td.get("name", "?")
        method = td.get("method", "?")
        path = td.get("path", "?")
        auth_summary = _format_auth_summary(td, tabby_profile_id)
        lines.append(f"| `{name}` | `{method}` | `{path}` | {auth_summary} |")
    lines.append("")

    # ── Per-tool sections ─────────────────────────────────────────────────────
    for td in tool_defs:
        lines.extend(_format_tool_section(td, tabby_profile_id))
        lines.append("")

    # ── Custom-fenced notes (survive regeneration) ────────────────────────────
    lines.append("## Notes")
    lines.append("")
    lines.append("<!-- custom:start:api-notes -->")
    lines.append(
        "<!-- Add hand-written API notes here; this region survives `mcp docs` / `skill docs`. -->"
    )
    lines.append("<!-- custom:end:api-notes -->")
    lines.append("")

    rendered = "\n".join(lines)
    if existing:
        from noui_core.compile.markdown_sections import merge_custom_sections

        rendered = merge_custom_sections(existing, rendered)
    return rendered


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _format_auth_summary(td: dict, tabby_profile_id: str) -> str:
    auth_headers: list[str] = td.get("auth_headers", [])
    auth_cookies: list[str] = td.get("auth_cookies", [])

    if not auth_headers and not auth_cookies:
        if tabby_profile_id:
            return f"Tabby profile `{tabby_profile_id[:8]}…`"
        return "none"

    parts: list[str] = []
    if auth_headers:
        parts.append(f"headers: {', '.join(auth_headers)}")
    if auth_cookies:
        auth_source = td.get("auth_source", "")
        src = f"{auth_source} " if auth_source else ""
        cookie_names = ", ".join(f"`{c}`" for c in auth_cookies)
        parts.append(f"{src}cookies: {cookie_names}")
    return "; ".join(parts)


def _format_auth_detail(td: dict, tabby_profile_id: str) -> str:
    auth_headers: list[str] = td.get("auth_headers", [])
    auth_cookies: list[str] = td.get("auth_cookies", [])

    if not auth_headers and not auth_cookies:
        if tabby_profile_id:
            return f"Tabby profile `{tabby_profile_id[:8]}…`"
        return "none"

    parts: list[str] = []
    if auth_headers:
        names = ", ".join(f"`{h}`" for h in auth_headers)
        parts.append(f"headers: {names}")
    if auth_cookies:
        auth_source = td.get("auth_source", "")
        src_prefix = f"{auth_source.capitalize()} " if auth_source else ""
        names = ", ".join(f"`{c}`" for c in auth_cookies)
        parts.append(f"{src_prefix}cookies {names}")
    return "; ".join(parts)


def _format_tool_section(td: dict, tabby_profile_id: str) -> list[str]:
    lines: list[str] = []

    name = td.get("name", "?")
    description = td.get("description", "")
    method = td.get("method", "?")
    # Prefer explicit base_url; fall back to stripping path from url
    base_url = td.get("base_url") or _extract_base_url(td.get("url", ""))
    path = td.get("path", "?")
    content_type = td.get("request_content_type", "")
    response_status = td.get("response_status", "?")
    params: list[dict] = td.get("params", [])
    request_headers: list[dict] = td.get("request_headers", [])
    request_body: dict | None = td.get("request_body")

    lines.append(f"## `{name}`")
    lines.append("")
    if description:
        lines.append(description)
        lines.append("")

    lines.append(f"- **Method:** `{method}`")
    lines.append(f"- **Base URL:** `{base_url}`")
    lines.append(f"- **Path:** `{path}`")
    if content_type:
        lines.append(f"- **Content type:** `{content_type}`")
    lines.append(f"- **Recorded response status:** `{response_status}`")
    lines.append(f"- **Auth:** {_format_auth_detail(td, tabby_profile_id)}")
    lines.append("")

    # ── Parameters table ──────────────────────────────────────────────────────
    lines.append("### Parameters")
    lines.append("")
    if params:
        lines.append("| Name | Type | Required | Source | Description |")
        lines.append("|---|---|---:|---|---|")
        for p in params:
            pname = p.get("name", "?")
            ptype = p.get("type", "string")
            req = "yes" if p.get("required", False) else "no"
            source = p.get("source", _infer_source(pname, path, method))
            desc = p.get("description", "")
            lines.append(f"| `{pname}` | {ptype} | {req} | {source} | {desc} |")
    else:
        lines.append("None — this tool takes no parameters.")
    lines.append("")

    # ── Request Notes ─────────────────────────────────────────────────────────
    lines.append("### Request Notes")
    lines.append("")

    # Resolve effective source for each param (may be missing in generalized tools.json)
    def _effective_source(p: dict) -> str:
        return p.get("source") or _infer_source(p.get("name", ""), path, method)

    query_params = [p for p in params if _effective_source(p) == "query"]
    body_params = [p for p in params if _effective_source(p) == "body"]

    if query_params:
        qnames = ", ".join(f"`{p['name']}`" for p in query_params)
        lines.append(f"- Query parameters: {qnames}")
    else:
        lines.append("- Query parameters: none")

    if body_params:
        bnames = ", ".join(f"`{p['name']}`" for p in body_params)
        lines.append(f"- Body parameters: {bnames}")
    else:
        lines.append("- Body parameters: none")

    # Static headers: exclude auth/cookie/sensitive ones
    static_headers = [
        h["name"] for h in request_headers if h.get("name", "").lower() not in _AUTH_HEADER_NAMES
    ]
    if static_headers:
        hnames = ", ".join(f"`{h}`" for h in static_headers)
        lines.append(f"- Static request headers: {hnames}")
    else:
        lines.append("- Static request headers: none documented")

    # ── Captured body shape (redacted) ────────────────────────────────────────
    if request_body and isinstance(request_body, dict):
        body_shape = _schema_like_body(request_body)
        if body_shape:
            lines.append("")
            lines.append("#### Captured Body Shape (redacted)")
            lines.append("")
            lines.append("```")
            lines.append(body_shape)
            lines.append("```")

    return lines


def _infer_source(param_name: str, path: str, method: str) -> str:
    """Best-effort source inference when the tool_def omits the source field."""
    if f"{{{param_name}}}" in path:
        return "path"
    if method in ("GET", "DELETE", "HEAD"):
        return "query"
    return "body"


def _extract_base_url(url: str) -> str:
    """Strip path from a full URL to get the base."""
    if not url:
        return "?"
    try:
        from urllib.parse import urlparse  # lazy import; pure-stdlib

        p = urlparse(url)
        return f"{p.scheme}://{p.netloc}"
    except Exception:
        return url


def _schema_like_body(body: dict, indent: int = 0) -> str:
    """Return a type-sketch of the request body with sensitive values redacted."""
    if not body or not isinstance(body, dict):
        return ""
    prefix = "  " * indent
    rows: list[str] = ["{"]
    for key, val in body.items():
        if key.lower() in _SENSITIVE_BODY_KEYS:
            rows.append(f"{prefix}  {key}: <redacted>")
        elif isinstance(val, dict):
            rows.append(f"{prefix}  {key}: {_schema_like_body(val, indent + 1)}")
        elif isinstance(val, list):
            rows.append(f"{prefix}  {key}: [...]")
        elif isinstance(val, bool):
            rows.append(f"{prefix}  {key}: <bool>")
        elif isinstance(val, int):
            rows.append(f"{prefix}  {key}: <int>")
        elif isinstance(val, float):
            rows.append(f"{prefix}  {key}: <float>")
        else:
            rows.append(f"{prefix}  {key}: <string>")
    rows.append(f"{prefix}}}")
    return "\n".join(rows)
