query transactions($offset:Int, $limit:Int, $with:String, $filterBy:String, $orderBy:String){company{transactions(offset:$offset, limit:$limit, with:$with, filterBy:$filterBy, orderBy:$orderBy){edges{node{entityVersion id type customFields{value definition{id name schema{format}}}header{amount privateMemo transactionType txnDate referenceNumber txnStatus regionExtensions{defaultTxnSubType{txnSubTypeId}}contact{id displayName}currencyInfo{symbol currency homeAmount}is_ict_txn}traits{delivery{printStatus emailDeliveryInfo{to error}lastDelivered}prePayment{requestedAmount paidAmount prePayment}balance{balance dueDate aging}acceptStatus{acceptStatus acceptedBy acceptedDate}approval{status}tax{totalTaxAmount totalTaxableAmount}payment{paymentMethod{name id}paymentErrorDetails{errorLongMessage}}shipping{shipDate}}qboAppData{txnListProps{attachmentCount homeOpenBalance recentlyPaidDate eCloudStatus eCloudStatusInt txnTypeId txnType projectStatus}}}}}}}